function parse_git_branch {
   git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\[\033[35m\]\t\[\033[m\]-\[\033[36m\]\u\[\033[m\]\[\033[33;1m\]\w\[\033[m\]\$(parse_git_branch)$ "
#
# VirtualEnvWrapper
#
export WORKON_HOME=$HOME/.virtualenvs
export PATH=~/bin:$PATH
source /usr/local/bin/virtualenvwrapper.sh

alias ll='ls -al'

# some more ls aliases
alias la='ls -A'
alias l='ls -CF'

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
